version: 2
jobs:
  build:
    docker:
      - image: ubuntu
    steps:
      - checkout
      - run: pwd
  test:
    docker:
      - image: ubuntu
    steps:
      - checkout
      - run: pwd
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test