version: 2
jobs:
  build:
    docker:
      - image: rikorose/gcc-cmake:latest
    steps:
      - run: checkout
      - run:
          name: build application
          command: cmake --build . --target run_tests -- -j 2
  test:
    docker:
      - image: rikorose/gcc-cmake:latest
    steps:
      - run:
          name: run tests
          command: /bin/bash run_tests --gtest_filter=*
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
          filters:
            branches:
              only: master